<footer id="bgRodape" class="container">
	<div id="rodape" class="content">
		<div class="elements">
			<div class="ps">
				<p><?php echo $f5_rodape[infosDeContato][0][telefone]; ?></p>
				<p><?php echo $f5_rodape[infosDeContato][0][email]; ?></p>
			</div>
			<div class="shares">
				<ul>
					<li><a href="" class="iconFace"></a></li>
					<li><a href="" class="iconInstagram"></a></li>
				</ul>
			</div>
		</div>
	</div>
	<div id="finalfooter" class="content">
		<p class="copyright">
			© <?php echo date('Y'); ?> - Paula  Reichert. Todos os direitos reservados.
		</p>
		<p class="desenvolvido">
			Desenvolvido por <a href="http://www.f5digital.com.br" target="blanck" title="F5 Digital">F5 Digital</a>
		</p>
		<div class="clear"></div>
	</div>
</footer>