<!DOCTYPE HTML>
<html lang="pt-br">
<head>
	<title>SOS Feevale</title>
	<!--meta-->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="robots" content="index,follow" />
	<meta name="author" content="F5 Digital" />
	<meta name="copyright" content="Copyright ©2016 - SOS Feevale" />
	<meta name="keywords" content="" />
	<meta name="description" content="SOS Feevale" />
	<!--style-->
	<link rel="shortcut icon" href="<?php echo IMG; ?>favicon.png"/>
	<link rel="stylesheet" href="<?php echo CSS; ?>reset.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo CSS; ?>estilo.css" type="text/css" />
	<link rel="stylesheet" type="text/css" href="<?php echo PLUGINS; ?>shadowbox/shadowbox.css">
	
	<meta property="fb:app_id" content="123456" />
	<meta property="og:title" content="SOS Feevale" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="" />
	<meta property="og:image" content="" />
	<meta property="og:site_name" content="SOS Feevale" />
	<meta property="og:description" content="" />
</head>
<body>
<div id="center">
	
	<main role="main">
	
		<div class="container">
			<div class="content">
				TESTE
			</div>
		</div>

	</main>
	
</div>

<!-- SCRIPTs -->
	<script type="text/javascript" src="<?php echo JS; ?>jquery-1.11.3.min.js"></script>
	<script type="text/javascript" src="<?php echo JS; ?>jquery-ui.min.js"></script>
	<script type="text/javascript" src="<?php echo JS; ?>funcoes.js"></script>
	
	<script type="text/javascript" src="<?php echo PLUGINS; ?>shadowbox/shadowbox.js"></script>
	<script type="text/javascript">Shadowbox.init();</script>
	
	<script>
		$(document).ready(function(){
			
		});
	</script>
<!-- END - SCRIPTs -->
</body>
</html>