<!DOCTYPE html>

<!--
<b>Erro 404 View</b>
Esta página é exibida quando o usuário tentar ou ser levado para um controller ou action inexistente.
@copyright (c) Junho, 2015, Anderson B. Glaeser - F5 Digital.
-->

<html lang="pt-br">
    <head>
        <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
        <meta charset="utf-8" />
        <title>F5 Digital</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="F5 Digital" name="author" />

        <!-- INÍCIO DO FRAMEWORK CSS -->
        <link href="<?php echo PLUGINS; ?>boostrapv3/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo PLUGINS; ?>boostrapv3/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo PLUGINS; ?>font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo PLUGINS; ?>pace/pace-theme-flash.css" rel="stylesheet" type="text/css" media="screen"/>
        <link href="<?php echo PLUGINS; ?>jquery-slider/css/jquery.sidr.light.css" rel="stylesheet" type="text/css" media="screen"/>
        <!-- FIM DO FRAMEWORK CSS -->

        <!-- INÍCIO CSS DO TEMPLATE -->
        <link href="<?php echo CSS; ?>animate.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo CSS; ?>style.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo CSS; ?>responsive.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo CSS; ?>custom-icon-set.css" rel="stylesheet" type="text/css"/>
        <!-- END CSS DO TEMPLATE -->
    </head>

    <body class="error-body no-top">
        
        <!-- INÍCIO CONTAINER ERRO --> 
        <div class="error-wrapper container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4 col-sm-6">
                    <div class="error-container" >
                        <div class="error-main">
                            <div class="error-number">Erro 404</div>
                            <div class="error-description-mini" ><b>Mensagem: </b><br /><?php echo $f5_mensagem; ?>.</div>
                            <div class="error-description-mini">Entre em contato conosco, via suporte.</div>
                            <br>
                            <button class="btn btn-primary btn-cons" type="button" onclick="javascript:history.back()">Voltar</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div id="footer">
            <div class="error-container">
                <center><img src="<?php echo IMG; ?>logo.png" border="0" width="150px" /></center>
            </div>
        </div>
        <!-- FIM CONTAINER ERRO -->

        <!-- INÍCIO JS DO FRAMEWORK --> 
        <script src="<?php echo PLUGINS; ?>jquery-1.8.3.min.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>boostrapv3/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>breakpoints.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>jquery-block-ui/jqueryblockui.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>pace/pace.min.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>jquery-slider/jquery.sidr.min.js" type="text/javascript"></script>
        <script src="<?php echo PLUGINS; ?>jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <!-- FIM DO JS DO FRAMEWORK --> 
    </body>
</html>